### ISSUE TITLE
Workflows crashing

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-stats#80]
Hi @itsjackfan and @aliisona 

I am getting notification that workflows are crashing: https://github.com/ersilia-os/ersilia-stats/actions/runs/11925561979

I did not check what may be going on, just flagging it here in case it is useful.

Best,
Miquel

**Comment by itsjackfan** [comment]
The specific one you pointed to seems to be a rate limit. However, get stats also seems that it failed for the first time because the import was somehow broken. Will check the code out and see if it reproduces.
